name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t devops-app .

    - name: Run Test
      run: echo "App build successful"

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Image
      run: docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    - name: Deploy via VPN (Bastion)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@10.0.2.157 << 'EOF'
            echo "Killing any process using port 3000..."
            sudo fuser -k 3000/tcp || true

            echo "Stopping all containers..."
            docker ps -aq | xargs -r docker stop

            echo "Removing all containers..."
            docker ps -aq | xargs -r docker rm

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

            echo "Starting new container..."
            docker run -d -p 3000:3000 --name app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
          EOF
