name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Build Docker Image
    - name: Build Docker Image
      run: docker build -t devops-app .

    # 3. Basic Test
    - name: Run Test
      run: echo "App build successful"

    # 4. Login to Docker Hub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5. Tag Image
    - name: Tag Image
      run: docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    # 6. Push Image
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    # 7. Deploy via VPN (Bastion → Private EC2)
    - name: Deploy via VPN (Bastion)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@10.0.2.157 << 'EOF'
            echo "Stopping old container..."
            docker stop app || true
            
            echo "Removing old container..."
            docker rm app || true

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

            echo "Starting new container..."
            docker run -d -p 3000:3000 --name app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
          EOF
